name: Release
on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Run Semantic Release
        uses: codfish/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
