name: Release
on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [1.17.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Run Semantic Release
        id: semantic
        uses: docker://ghcr.io/codfish/semantic-release-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
